# READ MORE: https://www.spigotmc.org/wiki/plugin-yml/

name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.ArtemisPlugin
api-version: 1.17
depend: [CivModCore]
softdepend: []
authors: [Maxopoly]

permissions:
    artemis.tp:
      description: Gives access to the teleport command
      default: op