# READ MORE: https://www.spigotmc.org/wiki/plugin-yml/

name: ${project.name}

version: ${project.version}

main: ${project.groupId}.${project.artifactId}.ArtemisPlugin

api-version: 1.14

depend: [CivModCore]

softdepend: []

authors: [Maxopoly]

commands:
  stp:
    aliases:
    - shardteleport
    usage: /stp
    description: Teleports you somewhere
    min-args: 1
    max-args: 5
    player-only: false
    permission: artemis.tp
permissions:
    artemis.tp:
      description: Gives access to the teleport command
      default: op